Fixed git-license command.

diff --git a/git/commands/git-license b/git/commands/git-license
--- a/git/commands/git-license
+++ b/git/commands/git-license
@@ -7,7 +7,7 @@ declare -a LicenseArray=("MIT" "BSD" "GPLv2" "GPLv3" "Apache" "AGPLv3" "LGPLv2" 
 
 put_license()
 {
-    cp $HOME/.dotfiles/share/license/$1 $pwd
+    cp $HOME/.dotfiles/share/license/$1 $(pwd)/LICENSE
 }
 
 read_license()
@@ -16,19 +16,20 @@ read_license()
 
         if  [[ $1 -eq $License ]]
         then
-            if [[-f $HOME/.dotfiles/share/license/$1 ]]
+            if [[ -f $HOME/.dotfiles/share/license/$1 ]]
             then
-                less $HOME/.dotfiles/share/license $1
+                less $HOME/.dotfiles/share/license/$1
                 exit 0
             else
                 echo "License file \"$1\" not exists."
                 exit 1
             fi
-        else
-            echo "License \"$1\" not found. "
-            exit 1
         fi
     done
+
+    echo "License \"$1\" not found. "
+
+    exit 1
 }
 
 if_license()
@@ -37,7 +38,7 @@ if_license()
 
         if  [[ $1 -eq $License ]]
         then
-            if [[-f $HOME/.dotfiles/share/license/$1 ]]
+            if [[ -f $HOME/.dotfiles/share/license/$1 ]]
             then
                 put_license $1
                 echo "Your repository licensed with \"$1\" license agreement."
@@ -46,11 +47,11 @@ if_license()
                 echo "License file \"$1\" not exists."
                 exit 1
             fi
-        else
-            echo "License \"$1\" not found. "
-            exit 1
         fi
     done
+    echo "License \"$1\" not found. "
+
+    exit 1
 }
 
 list()
