Huge git changes
* Commands:
    git-latest-author: Shows branches and their latest author/commit and last modification time.
    git-license: Licenses your codes.
    git-stats: Shows repository statistics
* Aliases:
    contributor: Lists contributors of a repository and contributor statistics
* Licenses:
    Added need license by git-license command

diff --git a/git/commands/git-license b/git/commands/git-license
--- a/git/commands/git-license
+++ b/git/commands/git-license
@@ -3,11 +3,32 @@
 
 # Open a Git remote in the browser
 
-declare -a LicenseArray=("MIT" "BSD" "GPLv2" "GPLv3" "Apache" "AGPLv3" "LGPLv2" "LGPLv3" "EPL" "CC0" )
+declare -a LicenseArray=("MIT" "BSD" "GPLv2" "GPLv3" "Apache" "AGPLv3" "LGPLv2" "LGPLv3" "EPL" "CC0" "WTFPL")
 
 put_license()
 {
-    cp $HOME/.local/share/license/$1 $pwd
+    cp $HOME/.dotfiles/share/license/$1 $pwd
+}
+
+read_license()
+{
+    for License in ${LicenseArray[@]}; do
+
+        if  [[ $1 -eq $License ]]
+        then
+            if [[-f $HOME/.dotfiles/share/license/$1 ]]
+            then
+                less $HOME/.dotfiles/share/license $1
+                exit 0
+            else
+                echo "License file \"$1\" not exists."
+                exit 1
+            fi
+        else
+            echo "License \"$1\" not found. "
+            exit 1
+        fi
+    done
 }
 
 if_license()
@@ -16,9 +37,17 @@ if_license()
 
         if  [[ $1 -eq $License ]]
         then
-           put_license $1
+            if [[-f $HOME/.dotfiles/share/license/$1 ]]
+            then
+                put_license $1
+                echo "Your repository licensed with \"$1\" license agreement."
+                exit 0
+            else
+                echo "License file \"$1\" not exists."
+                exit 1
+            fi
         else
-            echo "License \"$l\" not found. "
+            echo "License \"$1\" not found. "
             exit 1
         fi
     done
@@ -41,6 +70,9 @@ do
                                 list
                                 ;;
         -h | --help )           git help license
+                                exit
+                                ;;
+        -r | --read )           read_license $1
                                 exit
                                 ;;
         * )                     if_license $1
